CREATE TABLE IF NOT EXISTS `autos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero_de_poliza` VARCHAR(255),
  `nombre_contratante` VARCHAR(255),
  `rfc` VARCHAR(20),
  `aseguradora` VARCHAR(255),
  `tipo_de_vehiculo` VARCHAR(255),
  `marca` VARCHAR(255),
  `modelo` VARCHAR(255),
  `anio` INT,
  `placa` VARCHAR(50),
  `serie` VARCHAR(100),
  `fecha_inicio` DATE,
  `fecha_fin` DATE,
  `prima_neta` DECIMAL(15,2),
  `derecho_de_poliza` DECIMAL(15,2),
  `i_v_a` DECIMAL(15,2),
  `recargo_por_pago_fraccionado` DECIMAL(15,2),
  `pago_total_o_prima_total` DECIMAL(15,2),
  `forma_de_pago` VARCHAR(50),
  `status` VARCHAR(50) DEFAULT 'active',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_numero_poliza` (`numero_de_poliza`),
  INDEX `idx_nombre_contratante` (`nombre_contratante`),
  INDEX `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci; 